---
title: "microbenchmark-rdgidb"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{microbenchmark-rdgidb}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

This vignette microbenchmarks functions from rdgidb

## Load Packages

```{r setup, message=FALSE}
library(rdgidb)
library(microbenchmark)
library(httptest2)
```

```{r, include = FALSE}
httptest2::start_vignette("microbenchmark-rdgidb")
```

## Initalize Inputs

```{r inputs}
genes <- c("BRAF", "PDGFRA")
drugs <- c("Imatinib")
```

# Microbenchmarks

## get_drugs()

```{r benchmark-get-drugs, warning=FALSE}
httptest2::with_mock_api({
  microbenchmark(
    get_drugs(drugs),
    times = 1000
  )
})
```

## get_genes()

```{r benchmark-get-genes}
httptest2::with_mock_api({
  microbenchmark(
    get_genes(genes),
    times = 1000
  )
})
```

## get_interactions()

```{r benchmark-get-interactions}
# By Gene
httptest2::with_mock_api({
  microbenchmark(
    get_interactions(genes, search = "genes"),
    times = 1000
  )
})

# By Drug
httptest2::with_mock_api({
  microbenchmark(
    get_interactions(drugs, search = "drugs"),
    times = 1000
  )
})
```

## get_categories()

```{r benchmark-get-categories}
httptest2::with_mock_api({
  microbenchmark(
    get_categories(genes),
    times = 1000
  )
})
```

## get_sources()

```{r benchmark-get-sources}
httptest2::with_mock_api({
  microbenchmark(
    get_sources(),
    times = 1000
  )
})
```

```{r, include = FALSE}
httptest2::end_vignette()
```
