query getInteractionsByGene(
  $first: Int = 1000
  $names: [String!]
  $sourceDbName: String
  $pmid: Int
  $interactionType: String
  $after: String
) {
  genes(
    first: $first
    names: $names
    sourceDbName: $sourceDbName
    pmid: $pmid
    interactionType: $interactionType
    after: $after
  ) {
    nodes {
      interactions {
        interactionAttributes {
          name
          value
        }
        drug {
          name
          conceptId
          approved
        }
        gene {
          name
          longName
          conceptId
          geneCategories {
            name
          }
        }
        interactionScore
        interactionClaims {
          publications {
            citation
            pmid
          }
          source {
            sourceDbName
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
