query getDrugs(
  $first: Int = 1000
  $names: [String!]
  $immunotherapy: Boolean
  $antiNeoplastic: Boolean
  $after: String
) {
  drugs(
    first: $first
    names: $names
    immunotherapy: $immunotherapy
    antiNeoplastic: $antiNeoplastic
    after: $after
  ) {
    nodes {
      name
      conceptId
      drugAliases {
        alias
      }
      drugAttributes {
        name
        value
      }
      antiNeoplastic
      immunotherapy
      approved
      drugApprovalRatings {
        rating
        source {
          sourceDbName
        }
      }
      drugApplications {
        appNo
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
